@startuml Architektur_Grob
skinparam Style strictuml
skinparam genericDisplay old
skinparam classAttributeIconSize 0
skinparam monochrome true

component KontaktSplitter{

    component View{
        class MainView
    }

    component ViewModel{
        class MainViewViewModel{
            'ToDo Bindings
        }
    }

    component Model{
        class Contact{
            +salutation: string
            +lastName: string
            +firstName: string
            +titles: IEnumerable<string>
        }

        class ParseResult<M>{
            +model: M
            +success: boolean
            +errorMessages: IEnumerable<string>
        }

        enum Gender<<enum>>{
            MALE
            FEMALE
            NEUTRAL
        }
    }

    component Services{
        class TitleService{
            +SaveOrUpdateTitle(title: string, titleSalutation: string): boolean
            +GetTitles(): IEnumerable<string>
            +GetTitleSalutation(title: string): string
        }

        class SalutationService{
            +SaveOrUpdateSalutation(salutation: string, gender: Gender): boolean
            +GetSalutations(): IEnumerable<string>
            +GetGender(salutation: string): Gender
        }

        class ParserService{
            -titleService: TitleService
            -salutationService: SalutationService
            +ParseContact(contactInput: string): ParseResult<Contact>
        }
        
        class LetterSalutationService{
            -titleService: TitleService
            -salutationService: SalutationService
            +GenerateLetterSalutation(contact: Contact): string
        }
    }
}



MainView --> MainViewViewModel

'MainViewViewModel --> ParserService
'MainViewViewModel --> LetterSalutationService
'MainViewViewModel --> Contact
'MainViewViewModel --> TitleService
'MainViewViewModel --> SalutationService
MainViewViewModel --> Model
MainViewViewModel --> Services

LetterSalutationService --> TitleService
LetterSalutationService --> SalutationService
LetterSalutationService --> Contact

TitleService <-- ParserService
SalutationService <-- ParserService
Contact <-- ParserService
ParseResult <-- ParserService:<<bind>>M::Contact

SalutationService --> Gender

@enduml